services:
  bridgebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridgebot
    restart: always
    volumes:
      - ./src:/bridgebot/src:ro
      - ./dist:/bridgebot/dist
      - ./tsconfig.json:/bridgebot/tsconfig.json:ro
      - ./package.json:/bridgebot/package.json:ro
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MINECRAFT_PSEUDO=${MINECRAFT_PSEUDO}
      - MINECRAFT_EMAIL=${MINECRAFT_EMAIL}
      - MINECRAFT_PASSWORD=${MINECRAFT_PASSWORD}
